name: connect-ssh-test

run-name: ${{ github.actor }} is connecting to OVH via SSH

on: [push]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: tzzs/server-shell@v3                # action to connect to server via SSH
      with:                                     # can find secrets.vars in github/repo/Settings > Secrets and variables
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}  # is my local private ssh key for my ssh connection
        USERNAME: ${{secrets.SSH_USER}}
        IP: ${{secrets.HOST}}
        PORT: ${{secrets.PORT}}
        SHELL: |                                # add commands i want to execute on server
          "cd mediation_api && ls -a"